import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by ezweb",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <nav>
          <ol>
            <li><Link href="/read/1">html</Link></li>
            <li><Link href="/read/2">css</Link></li>
            <li><Link href="/read/3">javascript</Link></li>
          </ol>
        </nav>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><button>delete</button></li>
        </ul>

        </body>
    </html>
  );
}
